import { defineConfig } from "tsup";

export default defineConfig((options) => ({
  entry: [
    "src/alert.tsx",
    "src/auth-layout.tsx",
    "src/avatar.tsx",
    "src/badge.tsx",
    "src/button.tsx",
    "src/card.tsx",
    "src/checkbox.tsx",
    "src/combobox.tsx",
    "src/description-list.tsx",
    "src/dialog.tsx",
    "src/divider.tsx",
    "src/dropdown.tsx",
    "src/fieldset.tsx",
    "src/heading.tsx",
    "src/input.tsx",
    "src/link.tsx",
    "src/listbox.tsx",
    "src/navbar.tsx",
    "src/pagination.tsx",
    "src/radio.tsx",
    "src/select.tsx",
    "src/sidebar-layout.tsx",
    "src/sidebar.tsx",
    "src/stacked-layout.tsx",
    "src/switch.tsx",
    "src/table.tsx",
    "src/text.tsx",
    "src/textarea.tsx",
  ],
  format: ["cjs", "esm"],
  dts: true,
  external: ["react"],
  ...options,
}));
